### ISSUE TITLE
fix: #153 is not published

### ISSUE THREAD

**Issue by jjangga0214** [grafana/xk6-output-prometheus-remote#154]
Hi! 

I installed the dashboard([19665](https://grafana.com/grafana/dashboards/19665-k6-prometheus/)) yesterday, but it seems it's not changed by #153.

<img width="914" alt="스크린샷 2023-10-09 오후 12 16 18" src="https://github.com/grafana/xk6-output-prometheus-remote/assets/28584151/adb95e55-b46c-4305-8c8c-78cca1bd4e4d">

Was there a mistake from publication?

 Thanks!

**Comment by ppcano** [comment]
@jjangga0214, It worked well for me. 

I imported the dashboard with its ID: Dashboards/New/Import/ID 19665. . 

![Screenshot 2023-10-09 at 15 39 22](https://github.com/grafana/xk6-output-prometheus-remote/assets/825430/77c25217-1d26-422e-b094-e7f9c4bb2a10)

Please, try it again and let us know if the problem persists. Thanks!

**Comment by jjangga0214** [comment]
@ppcano Thanks for the confirmation!

I re-imported the dashboard into a fresh Grafana instance Today, but the issue is still there.

I use [`kube-prometheus-stack`](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) helm chart by the way, though I doubt if this causes the issue. 

```yaml
grafana:
  dashboards:
    default:
      k6:
        gnetId: 19665
        datasource: Prometheus
```

I live in South Korea, and guess maybe Grafana server's cache is not renewed..?
Would it be possible?
(I personally think the system should invalidate the cache once it detects the new upload.)

**Comment by ppcano** [comment]
@jjangga0214, have you tried to pass the `revision` option?


```yaml
grafana:
  dashboards:
    default:
      k6:
        gnetId: 19665
        revision: 2
        datasource: Prometheus
```
